---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: flask
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: flask
  labels:
    app: flask

spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      serviceAccountName: flask
      containers:
        - name: flask
          image: aserver1999/testingpy:latest
          ports:
            - name: web
              containerPort: 5000
            - name: admin
              containerPort: 5000


