---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.107
  ports:
    - protocol: TCP
      name: web
      port: 5000
  selector:
    app: flask
